### ISSUE TITLE
Set the viewport size? 

### ISSUE THREAD

**Issue by vibou** [Reewr/promise-phantom#15]
Hello again, 

Sorry again to ask a question here but: is it possible to set the viewport size? 

In direct phantomjs it is possible with page.viewportsize = {width, height}

Thanks for your help ;) 

Vincent.

**Comment by Reewr** [comment]
You can do this by using [page.set(name, value)](https://github.com/Reewr/promise-phantom/blob/master/docs/webpage.md#Page+set). All attributes that you would normally set through `page.nameOfVariable = someValue` you can do with that function.

Ex:

``` javascript
// Example of setting viewport using object
page.set('viewportSize', {width: 1920, height: 1080}).then(() => {});

// Example of setting viewport by setting the width and height individually
page.set('viewportSize.width', 1920).then(() => {});
page.set('viewportSize.height', 1080).then(() => {});
```

In order to retrieve the variables, you can use [page.get(name)](https://github.com/Reewr/promise-phantom/blob/master/docs/webpage.md#Page+get)

**Comment by vibou** [comment]
Thanks a lot ! ;)
