### ISSUE TITLE
`page.evaluate` doesn't work with arrow function

### ISSUE THREAD

**Issue by sindresorhus** [Reewr/promise-phantom#6]
This works:

``` js
page.evaluate(function () {

});
```

But with an arrow function it doesn't:

``` js
page.evaluate(() => {

});
```

Wild guess, it's the `fn.toString()` parsing that doesn't take into account arrow functions.

**Comment by Reewr** [comment]
That is exactly the case. The stringified version of `() => {}` is exactly the same. Since PhantomJS doesn't support ES6, it just fails when it tries to evaluate it. 

I actually saw you had troubles with it when I checked out your repo, and tried to do some research regarding it. As far as I can see there's two solutions:
1. Wait until PhantomJS supports ES6 (which may take a while), or;
2. Support some kind of ES6 to ES5 transpiling for those functions it affects (evaluate, setFn and some others), since just parsing the arrow function wouldn't always be enough.  

The latter option would probably require some heavy dependencies though. 

I'll try to look into it soon. If you have any other suggestions, I'd love to hear them.

**Comment by Reewr** [comment]
Considering that I'll need to include major dependencies in order to fix this issue, I think I'll instead make some checks to make sure you are not using arrow functions and in addition mention that this and all other evaluate functions should be using ES5.

**Comment by Reewr** [comment]
3.1.2 has been released and includes changes to the documentation to mention that ES6 in these types of functions aren't supported. Also added some checks for arrow functions in order to warn about using them.

Thanks for reporting the issue, by the way.
